tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/BuildSlacknotificationsBean.java
package slacknotifications.teamcity.extension.bean;

import jetbrains.buildServer.serverSide.SBuildType;
import slacknotifications.teamcity.TeamCityIdResolver;
import slacknotifications.teamcity.settings.SlackNotificationConfig;

import java.util.List;

public class BuildSlacknotificationsBean{
	
	private SBuildType sBuildType;
	private List<SlackNotificationConfig> buildConfigs;
	
	public BuildSlacknotificationsBean(SBuildType b, List<SlackNotificationConfig> c) {
		this.setsBuildType(b);
		this.setBuildConfigs(c);
	}

	public SBuildType getsBuildType() {
		return sBuildType;
	}

	public void setsBuildType(SBuildType sBuildType) {
		this.sBuildType = sBuildType;
	}

	public List<SlackNotificationConfig> getBuildSlackNotificationList() {
		return buildConfigs;
	}

	public void setBuildConfigs(List<SlackNotificationConfig> buildConfigs) {
		this.buildConfigs = buildConfigs;
	}
	
	public boolean hasBuilds(){
		return !this.buildConfigs.isEmpty();
	}
	
	public boolean hasNoBuildSlackNotifications(){
		return this.buildConfigs.isEmpty();
	}
	
	public boolean hasBuildSlackNotifications(){
		return !this.buildConfigs.isEmpty();
	}
	
	public int getBuildCount(){
		return this.buildConfigs.size();
	}
	
	public String getBuildExternalId(){
		return TeamCityIdResolver.getExternalBuildId(sBuildType);
	}
	public String getBuildName(){
		return sBuildType.getName();
	}
	
}

tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/ProjectAndBuildSlacknotificationsBean.java
package slacknotifications.teamcity.extension.bean;

import jetbrains.buildServer.serverSide.SBuildType;
import jetbrains.buildServer.serverSide.SProject;
import slacknotifications.teamcity.TeamCityIdResolver;
import slacknotifications.teamcity.settings.SlackNotificationConfig;
import slacknotifications.teamcity.settings.SlackNotificationProjectSettings;

import java.util.ArrayList;
import java.util.List;

public class ProjectAndBuildSlacknotificationsBean {
	SProject project;
	SlackNotificationProjectSettings slackNotificationProjectSettings;
	List<SlackNotificationConfig> projectSlacknotifications;
	List<BuildSlacknotificationsBean> buildSlacknotifications;
	
	public static ProjectAndBuildSlacknotificationsBean newInstance (SProject project, SlackNotificationProjectSettings settings, SBuildType sBuild) {
		ProjectAndBuildSlacknotificationsBean bean = new ProjectAndBuildSlacknotificationsBean();
		bean.project = project;
		bean.slackNotificationProjectSettings = settings;
		
		bean.projectSlacknotifications = settings.getProjectSlackNotificationsAsList();
		bean.buildSlacknotifications = new ArrayList<BuildSlacknotificationsBean>();
		
		if (sBuild != null && sBuild.getProjectId().equals(project.getProjectId())){
			bean.buildSlacknotifications.add(new BuildSlacknotificationsBean(sBuild, settings.getBuildSlackNotificationsAsList(sBuild)));
		}
		return bean;
	}

	public int getProjectSlacknotificationCount(){
		return this.projectSlacknotifications.size();
	}

	public int getBuildSlacknotificationCount(){
		return this.buildSlacknotifications.size();
	}
	
	public SProject getProject() {
		return project;
	}

	public SlackNotificationProjectSettings getSlackNotificationProjectSettings() {
		return slackNotificationProjectSettings;
	}

	public List<SlackNotificationConfig> getProjectSlacknotifications() {
		return projectSlacknotifications;
	}

	public List<BuildSlacknotificationsBean> getBuildSlacknotifications() {
		return buildSlacknotifications;
	}
	
	public String getExternalProjectId(){
		return TeamCityIdResolver.getExternalProjectId(project);
	}

}

tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/ProjectSlackNotificationsBean.java
package slacknotifications.teamcity.extension.bean;

import jetbrains.buildServer.serverSide.SBuildType;
import jetbrains.buildServer.serverSide.SProject;
import slacknotifications.teamcity.BuildState;
import slacknotifications.teamcity.TeamCityIdResolver;
import slacknotifications.teamcity.settings.SlackNotificationConfig;
import slacknotifications.teamcity.settings.SlackNotificationMainSettings;
import slacknotifications.teamcity.settings.SlackNotificationProjectSettings;

import java.util.*;

public class ProjectSlackNotificationsBean {
	String projectId;
	Map<String, SlacknotificationConfigAndBuildTypeListHolder> slackNotificationList;
	
	
	public static ProjectSlackNotificationsBean build(SlackNotificationProjectSettings projSettings, SProject project, SlackNotificationMainSettings mainSettings){
		ProjectSlackNotificationsBean bean = new ProjectSlackNotificationsBean();
		List<SBuildType> projectBuildTypes = TeamCityIdResolver.getOwnBuildTypes(project);
		
		bean.projectId = TeamCityIdResolver.getInternalProjectId(project);
		bean.slackNotificationList = new LinkedHashMap<String, SlacknotificationConfigAndBuildTypeListHolder>();

		/* Create a "new" config with blank stuff so that clicking the "new" button has a bunch of defaults to load in */
		SlackNotificationConfig newBlankConfig = new SlackNotificationConfig("", "", "", true, new BuildState().setAllEnabled(), true, true, null, true, true);
		newBlankConfig.setUniqueKey("new");
		/* And add it to the list */
		addSlackNotificationConfigHolder(bean, projectBuildTypes, newBlankConfig, mainSettings);
		
		/* Iterate over the rest of the slacknotifications in this project and add them to the json config */
		for (SlackNotificationConfig config : projSettings.getSlackNotificationsAsList()){
			addSlackNotificationConfigHolder(bean, projectBuildTypes, config, mainSettings);
		}
		
		return bean;
		
	}
	
	public static ProjectSlackNotificationsBean build(SlackNotificationProjectSettings projSettings, SBuildType sBuildType, SProject project, SlackNotificationMainSettings mainSettings){
		ProjectSlackNotificationsBean bean = new ProjectSlackNotificationsBean();
		List<SBuildType> projectBuildTypes = TeamCityIdResolver.getOwnBuildTypes(project);
		Set<String> enabledBuildTypes = new HashSet<String>();
		enabledBuildTypes.add(sBuildType.getBuildTypeId());
		
		bean.projectId = TeamCityIdResolver.getInternalProjectId(project);
		bean.slackNotificationList = new LinkedHashMap<String, SlacknotificationConfigAndBuildTypeListHolder>();
		
		/* Create a "new" config with blank stuff so that clicking the "new" button has a bunch of defaults to load in */
		SlackNotificationConfig newBlankConfig = new SlackNotificationConfig("", "", "", true, new BuildState().setAllEnabled(), false, false, enabledBuildTypes, true, true);
		newBlankConfig.setUniqueKey("new");
		/* And add it to the list */
		addSlackNotificationConfigHolder(bean, projectBuildTypes, newBlankConfig, mainSettings);
		
		/* Iterate over the rest of the slacknotifications in this project and add them to the json config */
		for (SlackNotificationConfig config : projSettings.getBuildSlackNotificationsAsList(sBuildType)){
			addSlackNotificationConfigHolder(bean, projectBuildTypes, config, mainSettings);
		}
		
		return bean;
		
	}


	private static void addSlackNotificationConfigHolder(ProjectSlackNotificationsBean bean,
			List<SBuildType> projectBuildTypes, SlackNotificationConfig config, SlackNotificationMainSettings mainSettings) {
		SlacknotificationConfigAndBuildTypeListHolder holder = new SlacknotificationConfigAndBuildTypeListHolder(config, mainSettings);
		for (SBuildType sBuildType : projectBuildTypes){
			holder.addSlackNotificationBuildType(new SlacknotificationBuildTypeEnabledStatusBean(
													sBuildType.getBuildTypeId(), 
													sBuildType.getName(), 
													config.isEnabledForBuildType(sBuildType)
													)
										);
		}
		bean.slackNotificationList.put(holder.getUniqueKey(), holder);
	}
}

tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
package slacknotifications.teamcity.extension;

import jetbrains.buildServer.controllers.BaseController;
import jetbrains.buildServer.serverSide.SBuildServer;
import jetbrains.buildServer.serverSide.SProject;
import jetbrains.buildServer.serverSide.auth.Permission;
import jetbrains.buildServer.serverSide.settings.ProjectSettingsManager;
import jetbrains.buildServer.users.SUser;
import jetbrains.buildServer.web.openapi.PluginDescriptor;
import jetbrains.buildServer.web.openapi.WebControllerManager;
import jetbrains.buildServer.web.util.SessionUser;
import org.jetbrains.annotations.Nullable;
import org.springframework.web.servlet.ModelAndView;
import slacknotifications.SlackNotification;
import slacknotifications.teamcity.BuildState;
import slacknotifications.teamcity.BuildStateEnum;
import slacknotifications.teamcity.TeamCityIdResolver;
import slacknotifications.teamcity.extension.bean.ProjectSlackNotificationsBean;
import slacknotifications.teamcity.extension.bean.ProjectSlackNotificationsBeanJsonSerialiser;
import slacknotifications.teamcity.payload.SlackNotificationPayloadManager;
import slacknotifications.teamcity.settings.SlackNotificationContentConfig;
import slacknotifications.teamcity.settings.SlackNotificationMainSettings;
import slacknotifications.teamcity.settings.SlackNotificationProjectSettings;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;


public class SlackNotificationAjaxEditPageController extends BaseController {

	    private static final String PROJECT_ID = "projectId";
	    private static final String SLACK_NOTIFICATION = "slackNotifications";
	    private static final String SUBMIT_ACTION = "submitAction";
	    private static final String ERRORS_TAG = "<errors />";
	    private static final String MESSAGES = "messages";
	    private static final String CHANNEL = "channel";
	    private static final String SLACK_NOTIFICATION_ID = "slackNotificationId";
	    private static final String MAX_COMMITS_DISPLAY = "maxCommitsToDisplay";
	    private static final String BOT_NAME = "botName";
	    private static final String ICON_URL = "iconUrl";
	    private static final String FALSE = "false";
		protected static final String BEFORE_FINISHED = "BeforeFinished";
		protected static final String BUILD_INTERRUPTED = "BuildInterrupted";
		protected static final String BUILD_STARTED = "BuildStarted";
		protected static final String BUILD_BROKEN = "BuildBroken";
		protected static final String BUILD_FIXED = "BuildFixed";
		protected static final String BUILD_FAILED = "BuildFailed";
		protected static final String BUILD_SUCCESSFUL = "BuildSuccessful";
		
		
		private final WebControllerManager myWebManager;
    private final SlackNotificationMainSettings myMainSettings;
    private SBuildServer myServer;
	    private ProjectSettingsManager mySettings;
	    private final String myPluginPath;
	    private final SlackNotificationPayloadManager myManager;

	public SlackNotificationAjaxEditPageController(SBuildServer server, WebControllerManager webManager,
                                                       ProjectSettingsManager settings, SlackNotificationProjectSettings whSettings, SlackNotificationPayloadManager manager,
                                                       PluginDescriptor pluginDescriptor, SlackNotificationMainSettings mainSettings) {
	        super(server);
	        myWebManager = webManager;
	        myServer = server;
	        mySettings = settings;
	        myPluginPath = pluginDescriptor.getPluginResourcesPath();
	        myManager = manager;
            myMainSettings = mainSettings;
	    }

	    public void register(){
	      myWebManager.registerController("/slacknotifications/ajaxEdit.html", this);
	    }
	    
	    protected static void checkAndAddBuildState(HttpServletRequest r, BuildState state, BuildStateEnum myBuildState, String varName){
	    	if ((r.getParameter(varName) != null)
	    		&& ("on".equalsIgnoreCase(r.getParameter(varName)))){
	    		state.enable(myBuildState);
	    	} else {
	    		state.disable(myBuildState);;
	    	}
	    }
	    
	    protected static void checkAndAddBuildStateIfEitherSet(HttpServletRequest r, BuildState state, BuildStateEnum myBuildState, String varName, String otherVarName){
	    	if ((r.getParameter(varName) != null)
	    			&& ("on".equalsIgnoreCase(r.getParameter(varName)))){
	    		state.enable(myBuildState);
	    	} else if ((r.getParameter(otherVarName) != null)
	    			&& ("on".equalsIgnoreCase(r.getParameter(otherVarName)))){
		    	state.enable(myBuildState);
	    	} else {
	    		state.disable(myBuildState);;
	    	}
	    }

	    @Nullable
		@Override
	    protected ModelAndView doHandle(HttpServletRequest request, HttpServletResponse response) throws Exception {
	    	
	        HashMap<String,Object> params = new HashMap<String,Object>();
	        
	        SUser myUser = SessionUser.getUser(request);
	        SProject myProject;
	        SlackNotificationProjectSettings projSettings = null;

	    	if ("post".equalsIgnoreCase(request.getMethod())){
	    		if ((request.getParameter(PROJECT_ID) != null)
	    			&& request.getParameter(PROJECT_ID).startsWith("project")){
	    		    	projSettings = (SlackNotificationProjectSettings) mySettings.getSettings(request.getParameter(PROJECT_ID), SLACK_NOTIFICATION);
	    		    	myProject = this.myServer.getProjectManager().findProjectById(request.getParameter(PROJECT_ID));

			    		if ((projSettings != null) && (myProject != null)
			    				&& (myUser.isPermissionGrantedForProject(myProject.getProjectId(), Permission.EDIT_PROJECT))){
			    			if ((request.getParameter(SUBMIT_ACTION) != null ) 
			    				&& ("removeSlackNotification".equals(request.getParameter(SUBMIT_ACTION)))
			    				&& (request.getParameter("removedSlackNotificationId") != null)){
			    					projSettings.deleteSlackNotification(request.getParameter("removedSlackNotificationId"), myProject.getProjectId());
			    					if(projSettings.updateSuccessful()){
			    						myProject.persist();
			    						params.put(MESSAGES, ERRORS_TAG);
			    					} else {
			    						params.put(MESSAGES, "<errors><error id=\"messageArea\">The slacknotifications was not found. Have the SlackNotifications been edited on disk or by another user?</error></errors>");
			    					}
			    					
			    			} else if ((request.getParameter(SUBMIT_ACTION) != null ) 
				    				&& ("updateSlackNotification".equals(request.getParameter(SUBMIT_ACTION)))){
			    				if((request.getParameter(CHANNEL) != null )
				    				&& (request.getParameter(CHANNEL).length() > 0 )){
			    					
			    					if (request.getParameter(SLACK_NOTIFICATION_ID) != null){
			    						Boolean enabled = false;
                                        Boolean mentionChannelEnabled = false;
										Boolean mentionSlackUserEnabled = false;
			    						Boolean buildTypeAll = false;
			    						Boolean buildTypeSubProjects = false;
                                        SlackNotificationContentConfig content = new SlackNotificationContentConfig();
			    						Set<String> buildTypes = new HashSet<String>();
			    						if ((request.getParameter("slackNotificationsEnabled") != null )
			    								&& ("on".equalsIgnoreCase(request.getParameter("slackNotificationsEnabled")))){
			    							enabled = true;
			    						}
                                        if ((request.getParameter("mentionChannelEnabled") != null )
                                                && ("on".equalsIgnoreCase(request.getParameter("mentionChannelEnabled")))){

                                            mentionChannelEnabled = true;
                                        }
										if ((request.getParameter("mentionSlackUserEnabled") != null )
												&& ("on".equalsIgnoreCase(request.getParameter("mentionSlackUserEnabled")))){
											mentionSlackUserEnabled = true;
										}

                                        content.setEnabled((request.getParameter("customContentEnabled") != null )
                                                && ("on".equalsIgnoreCase(request.getParameter("customContentEnabled"))));

                                        if (content.isEnabled()){

                                            if ((request.getParameter(MAX_COMMITS_DISPLAY) != null )
                                                    && (request.getParameter(MAX_COMMITS_DISPLAY).length() > 0)){
                                                content.setMaxCommitsToDisplay(convertToInt(request.getParameter(MAX_COMMITS_DISPLAY), SlackNotificationContentConfig.DEFAULT_MAX_COMMITS));
                                            }

                                            content.setShowBuildAgent((request.getParameter("showBuildAgent") != null )
                                                    && ("on".equals(request.getParameter("showBuildAgent"))));

                                            content.setShowCommits((request.getParameter("showCommits") != null )
                                                    && ("on".equalsIgnoreCase(request.getParameter("showCommits"))));

                                            content.setShowCommitters((request.getParameter("showCommitters") != null)
                                                    && ("on".equalsIgnoreCase(request.getParameter("showCommitters"))));

                                            content.setShowElapsedBuildTime((request.getParameter("showElapsedBuildTime") != null)
                                                    && ("on".equalsIgnoreCase(request.getParameter("showElapsedBuildTime"))));

                                            content.setShowFailureReason((request.getParameter("showFailureReason") != null)
                                                    && ("on".equalsIgnoreCase(request.getParameter("showFailureReason"))));

tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/ajaxEdit.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/xml" %>
<response>${messages}</response>

tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/buildSlackNotificationTab.jsp
<%@ include file="/include.jsp" %>
	<div><h3 class="title">Slack notifications configured for ${projectName}</h3>
	
<c:if test="${noProjectSlackNotifications}" >
		<div style='margin-left: 1em; margin-right:1em;'>
		<p>There are no Slack notifications configured for this project.</p>
		<a href="./slacknotifications/index.html?projectId=${projectExternalId}">Add project SlackNotifications</a>.
		</div>
	</div>
</c:if>
<c:if test="${projectSlackNotifications}" >
		<div style='margin-left: 1em; margin-right:1em;'>
		<c:if test="${projectSlackNotificationsDisabled}" >
			<div><strong>WARNING: Slack notification processing is currently disabled for this project</strong></div>
		</c:if>
		<p>There are <strong>${projectSlackNotificationCount}</strong> Slack notifications configured for all builds in this project.
			<a href="./slacknotifications/index.html?projectId=${projectExternalId}">Edit project Slack notifications</a>.</p>
		<table class="testList dark borderBottom">
			<thead><tr><th class=name>Channel</th><th class=name>Enabled</th></tr></thead>
			<tbody>
			<c:forEach items="${projectSlackNotificationList}" var="notification">
				<tr><td><c:out value="${notification.channel}" /></td><td><c:out value="${notification.enabledListAsString}" /></td></tr>
			</c:forEach>
			</tbody>
		</table>
		</div>
	</div>
</c:if>

<div style='margin-top: 2.5em;'><h3 class="title">Slack notifications configured for ${projectName} &gt; ${buildName}</h3>

<c:if test="${noBuildSlackNotifications}" >
		<div style='margin-left: 1em; margin-right:1em;'>
		<p>There are no Slack notifications configured for this specific build.</p>
		<a href="./slacknotifications/index.html?buildTypeId=${buildExternalId}">Add build Slack notifications</a>.
		</div>
	</div>
</c:if>
<c:if test="${buildSlackNotifications}" >
		<div style='margin-left: 1em; margin-right:1em;'>
		<p>There are <strong>${buildSlackNotificationCount}</strong> Slack notifications for this specific build.
			<a href="./slacknotifications/index.html?buildTypeId=${buildExternalId}">Edit build Slack notifications</a>.</p>
		<table class="testList dark borderBottom">
			<thead><tr><th class=name>Channel</th><th class=name>Enabled</th></tr></thead>
			<tbody>
			<c:forEach items="${buildSlackNotificationList}" var="notification">
				<tr><td><c:out value="${notification.channel}" /></td><td><c:out value="${channel.enabledListAsString}" /></td></tr>
			</c:forEach>
			</tbody>
		</table>
		</div>
	</div>
</c:if>

tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/projectSlackNotificationTab.jsp
<%@ include file="/include.jsp" %>
	<div>
	
	<c:forEach items="${projectAndParents}" var="project"> 
		<h3 class="title">Slack notifications configured for ${project.project.fullName}</h3>
		<c:if test="${project.projectSlacknotificationCount == 0}" >
				<div style='margin-left: 1em; margin-right:1em;'>
				<p>There are no Slack notifications configured for this project.</p>
				<a href="./slacknotifications/index.html?projectId=${project.externalProjectId}">Add project Slack notifications</a>.
				</div>
		</c:if>
		<c:if test="${project.projectSlacknotificationCount > 0}" >
				<div style='margin-left: 1em; margin-right:1em;'>
				<c:if test="${not project.slackNotificationProjectSettings.isEnabled()}" >
					<div><strong>WARNING: Slack notification processing is currently disabled for this project</strong></div>
				</c:if>
				<p>There are <strong>${project.projectSlacknotificationCount}</strong> Slack notifications configured for all builds in this project.
					<a href="./slacknotifications/index.html?projectId=${project.externalProjectId}">Edit project Slack notifications</a>.</p>
				<table class="testList dark borderBottom">
					<thead><tr><th class=name>Channel</th><th class=name>Enabled</th></tr></thead>
					<tbody>
					<c:forEach items="${project.projectSlacknotifications}" var="hook">
						<tr><td><c:out value="${hook.channel}" /></td><td><c:out value="${hook.enabledListAsString}" /></td></tr>
					</c:forEach>
					</tbody>
				</table>
				</div>
		</c:if>

			<c:forEach items="${project.buildSlacknotifications}" var="config">

				<div style='margin-top: 2.5em;'><h3 class="title">Slack notifications configured for ${projectName} &gt; ${config.buildName}</h3>
				
				<c:if test="${config.hasNoBuildSlackNotifications()}" >
						<div style='margin-left: 1em; margin-right:1em;'>
						<p>There are no Slack notifications configured for this specific build.</p>
						<a href="./slacknotifications/index.html?buildTypeId=${config.buildExternalId}">Add build Slack notifications</a>.
						</div>
					</div>
				</c:if>
				<c:if test="${config.hasBuildSlackNotifications()}" >
						<div style='margin-left: 1em; margin-right:1em;'>
						<p>There are <strong>${config.buildCount}</strong> Slack notifications for this specific build.
							<a href="./slacknotifications/index.html?buildTypeId=${config.buildExternalId}">Edit build Slack notifications</a>.</p>
						<table class="testList dark borderBottom">
							<thead><tr><th class=name>Channel</th><th class=name>Enabled</th></tr></thead>
							<tbody>
							<c:forEach items="${config.buildSlackNotificationList}" var="hook">
								<tr><td><c:out value="${hook.channel}" /></td><td><c:out value="${hook.enabledListAsString}" /></td></tr>
							</c:forEach>
							</tbody>
						</table>
						</div>
					</div>
				</c:if>
				
			</c:forEach>
			
		</c:forEach>
		</div>

tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/settingsList.jsp
<%@ page contentType="application/json;charset=UTF-8" language="java" session="true" errorPage="/runtimeError.jsp"
  %><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
  %><%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>
    ${projectSlackNotificationsAsJson}
  